apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-hwservice-app
  namespace: master
  annotations:
    kubernetes.io/ingress.class: nginx-cert
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - <custom domain>
    secretName: external-domain-tls
  rules:
  - host: <custom domain>
    http:
      paths:
      - path: /helloworld
        pathType: Prefix
        backend:
          service: 
            name: hwservice
            port: 
              number: 8080
